### ISSUE TITLE
Influx > 0.9 support?

### ISSUE THREAD

**Issue by inthecloud247** [jkoelker/influxdb-collectd-write#3]
Great plugin! Any plans to support influxdb > 0.9?

**Comment by icook** [comment]
I'm no longer using this in production, and don't have a quick way to setup a dev enviroment unfortunately. Do you know what the blocker is?

**Comment by ruudboon** [comment]
I'm trying it now and having the following error

``` pytb
[2016-01-30 15:40:21] Traceback (most recent call last):
  File "/usr/local/lib/collectd/python/write_influxdb.py", line 101, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/collectd/python/write_influxdb.py", line 196, in _flush
    self._client.write_points(values)
  File "/usr/local/lib/python2.7/site-packages/influxdb/client.py", line 373, in write_points
    tags=tags)
  File "/usr/local/lib/python2.7/site-packages/influxdb/client.py", line 413, in _write_points
    self.send_packet(data)
  File "/usr/local/lib/python2.7/site-packages/influxdb/client.py", line 703, in send_packet
    data = make_lines(packet).encode('utf-8')
  File "/usr/local/lib/python2.7/site-packages/influxdb/line_protocol.py", line 117, in make_lines
    for field_key in sorted(point['fields'].keys()):
KeyError: u'fields'
```

**Comment by ruudboon** [comment]
The error is caused by the new schema layout of 0.9. https://docs.influxdata.com/influxdb/v0.9/concepts/08_vs_09/

I tried to rewrite the script but I'm not really familiar with Python so can't get it working.
Main problem is that every measurement that holds multiple values should be split into multiple measurements. See the migration part here

https://docs.influxdata.com/influxdb/v0.8/advanced_topics/schema_design/

@icook If you need a tester let me know.

**Comment by icook** [comment]
@ruudboon Having not worked with this stack recently, is there a reason to use this plugin over using influxdb's collectd support? Docs are here: https://github.com/influxdata/influxdb/blob/master/services/collectd/README.md

**Comment by ruudboon** [comment]
@icook I prefer the native influxDB you implemented method because it supports https and authentication.
